CREATE TABLE "income" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "account_id" int,
  "amount" real NOT NULL,
  "date" timestamp NOT NULL
);

CREATE TABLE "expenses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "account_id" int,
  "amount" real NOT NULL,
  "date" timestamp NOT NULL
);

CREATE TABLE "accounts" (
  "id" serial PRIMARY KEY,
  "user_id" int UNIQUE,
  "balance" real NOT NULL
);

CREATE TABLE "income_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "color" varchar NOT NULL
);

CREATE TABLE "expense_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "color" varchar NOT NULL
);

CREATE TABLE "users" (
  "id" serial PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "hashed_password" varchar NOT NULL,
  "password_changed_at" timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "income" ("account_id");

CREATE INDEX ON "income" ("date");

CREATE INDEX ON "income" ("account_id", "date");

CREATE INDEX ON "expenses" ("account_id");

CREATE INDEX ON "expenses" ("date");

CREATE INDEX ON "expenses" ("account_id", "date");

CREATE INDEX ON "accounts" ("user_id");

CREATE INDEX ON "income_categories" ("name");

CREATE INDEX ON "expense_categories" ("name");

CREATE INDEX ON "users" ("name");

COMMENT ON COLUMN "income"."amount" IS 'Must be positive';

COMMENT ON COLUMN "expenses"."amount" IS 'Must be positive';

ALTER TABLE "income" ADD FOREIGN KEY ("category_id") REFERENCES "income_categories" ("id");

ALTER TABLE "income" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("category_id") REFERENCES "expense_categories" ("id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
