// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Accounts struct {
	ID      int32         `json:"id"`
	UserID  sql.NullInt32 `json:"user_id"`
	Balance float32       `json:"balance"`
}

type ExpenseCategories struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type Expenses struct {
	ID         int32         `json:"id"`
	CategoryID sql.NullInt32 `json:"category_id"`
	AccountID  sql.NullInt32 `json:"account_id"`
	// Must be positive
	Amount float32   `json:"amount"`
	Date   time.Time `json:"date"`
}

type Income struct {
	ID         int32         `json:"id"`
	CategoryID sql.NullInt32 `json:"category_id"`
	AccountID  sql.NullInt32 `json:"account_id"`
	// Must be positive
	Amount float32   `json:"amount"`
	Date   time.Time `json:"date"`
}

type IncomeCategories struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type Users struct {
	ID                int32     `json:"id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
