// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accounts, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategories, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateIncomeCategory(ctx context.Context, arg CreateIncomeCategoryParams) (IncomeCategories, error)
	CreateUser(ctx context.Context, name string) (Users, error)
	DeleteExpenseCategory(ctx context.Context, id int32) error
	DeleteIncome(ctx context.Context, id int32) error
	DeleteIncomeCategory(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Accounts, error)
	GetExpenseCategory(ctx context.Context, id int32) (ExpenseCategories, error)
	GetIncome(ctx context.Context, id int32) (Income, error)
	GetIncomeCategory(ctx context.Context, id int32) (IncomeCategories, error)
	GetTotalIncomeByAccountAndDate(ctx context.Context, arg GetTotalIncomeByAccountAndDateParams) (interface{}, error)
	GetUser(ctx context.Context, id int32) (Users, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Accounts, error)
	ListExpenseCategories(ctx context.Context, arg ListExpenseCategoriesParams) ([]ExpenseCategories, error)
	ListIncomeByAccountAndDate(ctx context.Context, arg ListIncomeByAccountAndDateParams) ([]Income, error)
	ListIncomeCategories(ctx context.Context, arg ListIncomeCategoriesParams) ([]IncomeCategories, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateExpenseCategoryColor(ctx context.Context, arg UpdateExpenseCategoryColorParams) (ExpenseCategories, error)
	UpdateExpenseCategoryName(ctx context.Context, arg UpdateExpenseCategoryNameParams) (ExpenseCategories, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateIncomeCategoryColor(ctx context.Context, arg UpdateIncomeCategoryColorParams) (IncomeCategories, error)
	UpdateIncomeCategoryName(ctx context.Context, arg UpdateIncomeCategoryNameParams) (IncomeCategories, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
